name             'zabbix_part'
version          '0.0.1'
description      'Installs/Configures zabbix server ant agent'
license          'Apache v2.0'
maintainer       'TIS Inc.'
maintainer_email 'ccndctr@gmail.com'

supports 'redhat', '>= 5.0'
supports 'centos', '>= 5.0'
depends 'apache2', '>= 1.0.8'
depends 'database', '>= 1.3.0'
depends 'mysql', '>= 1.3.0'
depends 'yum'
depends 'postgresql'
depends 'chocolatey'
depends 'java'
depends 'oracle-instantclient'
depends 'php'
depends 'yum-epel'
depends 'mysql-chef_gem'
