AllCops:
  Exclude:
    - cookbooks/**/*
    - vendor/**/*

LineLength:
  Max: 130
  Exclude:
    - site-cookbooks/zabbix_part/resources/auto_registration.rb

MethodLength:
  Max: 20

AbcSize:
  Enabled: false

AsciiComments:
  Enabled: false

Documentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

NumericLiterals:
  MinDigits: 7
