default['zabbix']['server']['version'] = '2.2.6'
default['zabbix']['web']['install_method'] = 'apache'
default['zabbix']['database']['dbpassword'] = 'ilikerandompasswords'
default['mysql']['version'] = '5.6'
default['zabbix_part']['auto_registration']['template'] = 'Template OS Linux'
